## Problem Statement

You are a data scientist / AI engineer at a meteorological consulting firm. You have been provided with a dataset named **"weather_data.csv"**, which includes detailed records of various weather conditions. The dataset comprises the following columns:

- **`hours_sunlight:`** The total number of hours of sunlight received in a day.
- **`humidity_level:`** The humidity level as a percentage.
- **`daily_temperature:`** The temperature recorded at the end of the day in degrees Celsius.

Your task is to use this dataset to build a linear regression model to predict the daily temperature based on the hours of sunlight and humidity level.

**Import Necessary Libraries**

In [1]:
#import necessary libraries
import pandas as pd
from sklearn.linear_model import LinearRegression



### Task 1: Train a Linear Regression with Single Variable

1. Import the data from the "weather_data.csv" file and store it in a variable df.
2. Display the number of rows and columns in the dataset.
3. Display the first few rows of the dataset to get an overview.
4. Create a Linear Regression model and fit it using only the `hours_sunlight` variable to predict `daily_temperature`.
5. Print the model's coefficient and intercept.
6. Predict the daily temperature with the following hours of sunlight:
   - 5 hours
   - 8 hours
   - 12 hours

In [2]:
# Step 1: Import the data from the "weather_data.csv" file and store it in a variable 'df'
df = pd.read_csv("weather_data.csv")

# Step 2: Display the number of rows and columns in the dataset
print("rows: ", df.shape[0])
print("columns: ", df.shape[1])

# Step 3: Display the first few rows of the dataset to get an overview
df.head()


rows:  49
columns:  3


hours_sunlight  humidity_level  daily_temperature
0            10.5              65               22.3
1             9.2              70               21.0
2             7.8              80               18.5
3             6.4              90               17.2
4             8.1              75               19.4

In [9]:
# Step 4: Create a Linear Regression model and fit it using only the 'hours_sunlight' variable to predict 'daily_temperature'
model = LinearRegression()
model.fit(df[['hours_sunlight']], df['daily_temperature'])

LinearRegression()

In [10]:
# Step 5: Print the model's coefficient and intercept
model.coef_, model.intercept_

(array([1.36753934]), np.float64(8.533832092006133))

In [17]:
# Step 6: Predict the daily temperature for the following hours of sunlight: 5, 8, and 12
test = pd.DataFrame([
    {"hours_sunlight": 5},
    {"hours_sunlight": 8},
    {"hours_sunlight": 12}
    ])
predicted_temp = model.predict(test)

# Print the predicted temperatures
print(predicted_temp)

[15.37152878 19.4741468  24.94430415]


### Task 2: Train a Linear Regression with Multiple Variable

- Create a Linear Regression model and fit it using both `hours_sunlight` and `humidity_level` variables to predict `daily_temperature`.
- Print the model's coefficients and intercept.
- Predict the daily temperature for the following conditions:
    - Hours of sunlight: 5 hours, Humidity level: 60%
    - Hours of sunlight: 8 hours, Humidity level: 75%
    - Hours of sunlight: 12 hours, Humidity level: 50%

In [18]:
#Step1: Create a Linear Regression model and fit it using both 'hours_sunlight' and 'humidity_level' variables to predict 'daily_temperature'
model = LinearRegression()
model.fit(df[["hours_sunlight", "humidity_level"]], df["daily_temperature"])

LinearRegression()

In [19]:
#Step2: Print the model's coefficients and intercept
model.coef_, model.intercept_

(array([ 1.09803993, -0.05430624]), np.float64(14.833402427458843))

In [20]:
# Step3: Predict the daily temperature for the following conditions:
# Hours of sunlight: 5 hours, Humidity level: 60%
# Hours of sunlight: 8 hours, Humidity level: 75%
# Hours of sunlight: 12 hours, Humidity level: 50%

test = pd.DataFrame([
    {"hours_sunlight": 5, "humidity_level": 60},
    {"hours_sunlight": 8, "humidity_level": 75},
    {"hours_sunlight": 12, "humidity_level": 50},
])

model.predict(test)

array([17.06522775, 19.54475397, 25.29456968])

In [21]:
df

hours_sunlight  humidity_level  daily_temperature
0             10.5              65               22.3
1              9.2              70               21.0
2              7.8              80               18.5
3              6.4              90               17.2
4              8.1              75               19.4
5             11.0              60               24.0
6              5.5              85               16.0
7              9.8              68               21.7
8              7.2              77               19.0
9              6.0              88               17.0
10             8.7              72               20.2
11            10.0              66               22.5
12             4.3              92               15.0
13             7.5              78               18.7
14             6.8              83               17.5
15            11.2              62               24.3
16             5.9              89               16.8
17             8.3              74               19.6
18             9.0              71               20.8
19             7.0              82               18.3
20            10.1              64               22.7
21             8.6              73               20.1
22             6.5              87               17.1
23             9.5              69               21.2
24             7.3              79               18.8
25             5.4              86               16.2
26            10.8              61               23.8
27             8.9              70               20.9
28             6.7              84               17.4
29             9.1              72               21.0
30            11.1              63               24.1
31             5.8              88               16.7
32             8.4              74               19.7
33             7.1              81               18.4
34            10.2              65               22.4
35             6.6              85               17.3
36             9.7              67               21.5
37             7.4              78               18.6
38             6.1              86               16.9
39             8.8              73               20.5
40            10.3              64               22.6
41             5.7              89               16.6
42             7.6              76               18.9
43             9.3              71               21.1
44            10.9              62               23.9
45             6.2              84               17.0
46             8.2              75               19.3
47             9.4              70               21.3
48             7.9              77               19.1